# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install build dependencies
COPY package.json package-lock.json tsconfig.json .
COPY src ./src
COPY mcp-inspector ./mcp-inspector
RUN npm ci
RUN npm run build

# Production stage
FROM node:lts-alpine AS production
WORKDIR /app

# Copy package.json and install production dependencies
COPY package.json package-lock.json .
RUN npm ci --omit=dev

# Copy built artifacts
COPY --from=builder /app/dist ./dist

# Use production start script (stdio server)
ENTRYPOINT ["npm", "start"]
